using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnrealSense.Navigation;

namespace UnrealSense.IndexerCli
{
    /// <summary>
    /// Held-out evaluation set, generated by a fixed rule (not hand-picked): declarations found by UnrealSense.Core's
    /// independent DeclarationScanner in the given source roots, restricted to headers clangd indexed, shuffled with a
    /// fixed seed, kept when clangd reports at least 2 references inside the scoring scope, until per-kind quotas are met.
    /// </summary>
    static class HeldOut
    {
        public static int Run(string projectDir, string dbDir, string outPath, int seed, string[] roots, int types, int funcs, int fields, int enumValues, int maxAttempts)
        {
            var idxDir = Path.Combine(dbDir, ".cache", "clangd", "index");
            var clangdFiles = new HashSet<string>(Directory.GetFiles(idxDir, "*.idx").Select(f =>
            {
                var n = Path.GetFileNameWithoutExtension(f); // Name.h.HASH
                int dot = n.LastIndexOf('.');
                return dot > 0 ? n.Substring(0, dot) : n;
            }), StringComparer.OrdinalIgnoreCase);
            Console.WriteLine($"clangd index covers {clangdFiles.Count} files");
            var projectNorm = projectDir.Replace('\\', '/').TrimEnd('/') + "/";
            bool InScope(string f)
            {
                f = f.Replace('\\', '/');
                return f.StartsWith(projectNorm, StringComparison.OrdinalIgnoreCase) || clangdFiles.Contains(Path.GetFileName(f));
            }

            // identifiers used in the project's sources (cheap textual pre-filter: usages must live in what clangd indexed)
            var projectWords = new HashSet<string>(StringComparer.Ordinal);
            foreach (var f in Directory.EnumerateFiles(projectDir, "*.*", SearchOption.AllDirectories))
            {
                if (!(f.EndsWith(".cpp") || f.EndsWith(".h")) || f.Contains("\\Intermediate\\") && !f.Contains("\\UHT\\")) continue;
                foreach (var w in Words(File.ReadAllText(f))) projectWords.Add(w);
            }

            var candidates = new List<(string File, int Line, string Name, string Group)>();
            foreach (var root in roots)
            {
                if (!Directory.Exists(root)) { Console.WriteLine("missing root " + root); continue; }
                foreach (var f in Directory.EnumerateFiles(root, "*.h", SearchOption.AllDirectories).OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
                {
                    if (f.Contains("\\Intermediate\\") || f.Contains("\\ThirdParty\\") || !clangdFiles.Contains(Path.GetFileName(f))) continue;
                    List<Declaration> decls;
                    try { decls = DeclarationScanner.Scan(File.ReadAllText(f)); } catch (Exception) { continue; }
                    foreach (var d in decls)
                    {
                        string g = d.Kind switch
                        {
                            SymbolKind.Class or SymbolKind.Struct or SymbolKind.Enum or SymbolKind.Delegate => "type",
                            SymbolKind.Function => "function",
                            SymbolKind.Field or SymbolKind.Variable => "field",
                            SymbolKind.EnumValue => "enumvalue",
                            _ => null,
                        };
                        if (g == null || d.Name == null || d.Name.Length < 3 || !projectWords.Contains(d.Name)) continue;
                        candidates.Add((f, d.Line + 1, d.Name, g));
                    }
                }
            }
            Console.WriteLine($"{candidates.Count} candidate declarations");
            var rng = new Random(seed);
            var shuffled = candidates.OrderBy(_ => rng.Next()).ToList();
            var quota = new Dictionary<string, int> { ["type"] = types, ["function"] = funcs, ["field"] = fields, ["enumvalue"] = enumValues };

            using var session = new ClangdSession(dbDir, projectDir);
            var results = new JArray();
            var seen = new HashSet<string>();
            int attempts = 0;
            foreach (var c in shuffled)
            {
                if (quota.Values.Sum() == 0 || attempts >= maxAttempts) break;
                if (quota[c.Group] == 0) continue;
                attempts++;
                var lineText = File.ReadLines(c.File).Skip(c.Line - 1).FirstOrDefault() ?? "";
                int col = Oracle.IndexOfWord(lineText, c.Name) + 1;
                if (col <= 0) continue;
                var r = session.Query(c.File, c.Line, col);
                if (r == null) continue;
                int inScope = r.Refs.Count(x => InScope(x.File));
                var key = c.Group + ":" + r.Hover;
                Console.WriteLine($"[{attempts}] {c.Group,-9} {c.Name,-40} {r.Refs.Count,5} refs ({inScope} in scope) {r.Hover}");
                if (inScope < 2 || !seen.Add(key)) continue;
                quota[c.Group]--;
                results.Add(Oracle.ToJson(c.Group + " " + c.Name + " @" + Path.GetFileName(c.File) + ":" + c.Line, c.File, c.Line, col, r));
                File.WriteAllText(outPath, new JObject
                {
                    ["project"] = projectDir, ["rule"] = $"seed={seed}; roots={string.Join(";", roots)}; DeclarationScanner; >=2 refs in scope",
                    ["clangdFiles"] = new JArray(clangdFiles.OrderBy(x => x)), ["results"] = results,
                }.ToString());
            }
            Console.WriteLine($"kept {results.Count} queries after {attempts} attempts; remaining quota: {string.Join(", ", quota.Select(kv => kv.Key + "=" + kv.Value))}");
            return 0;
        }

        static IEnumerable<string> Words(string s)
        {
            int i = 0;
            while (i < s.Length)
            {
                if (char.IsLetter(s[i]) || s[i] == '_')
                {
                    int st = i;
                    while (i < s.Length && (char.IsLetterOrDigit(s[i]) || s[i] == '_')) i++;
                    yield return s.Substring(st, i - st);
                }
                else i++;
            }
        }
    }
}
